[system]
home = "/"
# Read/Write Device All
perms = "RW_DA"

[installer]
home = "/"
# Read/Write Device All
perms = "RW_DA"

[root]
home = "/usr/root"
# Read/Write Device Operating System
perms = "RW_DO"

[user]
home = "/usr/user"
# Read/Write Device Home
perms = "RW_DH"

[guest]
home = "/usr/guest"
# Read/Write Device Home
perms = "RW_DH"
